### ISSUE TITLE
Restructure client side

### ISSUE THREAD

**Issue by dviryamin** [TechAssembly/ruven#17]
I'm new to unity but the client side project looks little messy(I'm talking about project folder structure).
Can anyone that understand it make it more friendly so newbies can contribute there?
If the structure is good then maybe short explanation will help.

**Comment by gioragutt** [comment]
Basically all of the actual code sits in `Assets/Scripts`,
this is where everything we write sits.

**Comment by dviryamin** [comment]
OK thanks.
